
HOME_DIR=/home/mcverter
LFS_PROJECT_DIR=$HOME_DIR/ComputerScienceKubuntu/LFS
LFSBOOK_DIR=$LFS_PROJECT/lfs
BLFSBOOK_DIR=$LFS_PROJECT/blfs

DIRECTORY_DIR=$LFS_PROJECTHOME_DIR/documentation
HTML_DIR=$DIRECTORY_DIR/html
NOCHUNKS_DIR=$DIRECTORY_DIR/nochunks
TXT_DIR=$DIRECTORY_DIR/txt

mkdir $DIRECTORY_DIR
mkdir $HTML_DIR
mkdir $NOCHUNKS_DIR
mkdir $TXT_DIR



cd $LFSBOOK_DIR
make BASEDIR=$HTML_DIR
make BASEDIR=$NOCHUNKSDIR nochunks
lynx -dump $NOCHUNKSDIR > $TXT_DIR

